version: 2
jobs:
  build:
    docker:
      - image: debian:10
    steps:
      - checkout
      - run:
          name: install asdf
          command: |
            apt-get update && apt-get install --no-install-recommends -y git ca-certificates curl build-essential libssl-dev automake autoconf libncurses5-dev procps
            git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.7
            export PATH=~/.asdf/bin:$PATH

            asdf plugin add erlang
            asdf install erlang 22.2

            tar cjf installs.tar.bz2 -C /root/.asdf/ installs
      - store_artifacts:
        path: installs.tar.bz2

workflows:
  version: 2
  build:
    jobs:
      - build
